Implement mailing
Michael-Schaer/adress_report_helper pull request #1
Opened 2019-09-16 12:57 UTC by Vento-Nuenenen

Mailing via Mailgun implementieren. Nur Konzeptart...

2019-09-17 19:31 UTC, carlobeltrame requested changes

2019-09-17 19:31 UTC, carlobeltrame commented on view/send_mail.php
> +$mg = Mailgun::create('f8295afcfc44ec0af88d344f45a8af3a-c27bf672-305d27b4'); // For EU servers
API-Keys und andere Credentials sollten nicht in Git eingecheckt werden. Stattdessen würde ich dafür einen Eintrag im config/app.ini einrichten, den der User dann einmalig selber befüllen muss

2019-09-17 19:31 UTC, carlobeltrame commented on view/send_mail.php
> +$mg->messages()->send('sandbox06d4d0f9aa3e4b88a0c839aeba471302.mailgun.org', [
Falls dies irgendwo auf dem Internet deployed wird, werden wohl bald Spammer das Formular und somit den API-Key missbrauchen. Entweder nur lokal laufen lassen, oder mit irgendeiner Art von Authentifizierung schützen.

2019-09-17 19:55 UTC, Vento-Nuenenen commented on view/send_mail.php
> +$mg = Mailgun::create('f8295afcfc44ec0af88d344f45a8af3a-c27bf672-305d27b4'); // For EU servers
Ich gebe dir in beiden Punkten recht, es ist aber trotz dem so gewollt...
Der PR hier ist ein Konzeptart, also mit möglichst wenig Aufwand aufzeigen wo wir hin wollen.

Der API-Key ist nur für den Sandbox-Modus von Mailgun. Dieser erlaubt nur den Versand an eine festgelegte Mailadresse. Ein Spammer erhält also, trotz korrekter Konfiguration nur ne Fehlermeldung retour :D

2019-09-26 08:41 UTC, Vento-Nuenenen commented
Done

2019-09-26 08:41 UTC, closed without merging